kind: SealedSecret
apiVersion: bitnami.com/v1alpha1
metadata:
  name: memberlist
  namespace: metallb-system
  creationTimestamp: null
spec:
  template:
    metadata:
      name: memberlist
      namespace: metallb-system
      creationTimestamp: null
    data: null
  encryptedData:
    secretkey: AgAzmVuk3Am3SjSp813uMtbqO1NdBRGvTy2NqKHt3xDh7bTtGFKJuT3nojVf5/GxTDldXiuLhL48qnBgrRDO+pZAsMxAvsFC+TqfLLLMYpwsdaLg5reSfOTot1mCFg7fiBXPvBm8OwqCyk/H64fPiz17dl1MK8tEzDlLkJDQdzCQD6PzIHU2DqPuchgT6KT0N+MFIHvP4vKnvLrfn4dPR/rtfhcfiZfUvuP4ul91fuPs98BPvcf1KZEdj8KvdG1C3uI4qsqwtHiNC6+3ctHg71eJCyJeLGkJz7LGzkOrFr+C7SeqRp6Eu+hsIlUpCJnDyEuDSB5wTqhIlDm6Jl7ZHwSOGg/cSvz+EPuC8isAlO8BVgdE7fj6My+bZSDw4jk7gCXdi7c0MTazLOqmu7Bv37bp94B/GsaIUwXwJ9DLc9wrRzfCHQQFY/8f3icBFQTmA6ANyMkdBWKjUepKtTnzLVgwdF3/dDjnqHP0sayylv6UWuY+tfOKgNyt3jGmPkFFLkymeryujqLpBaE2GFyPqE12oJc+KhKUc/+c5JAE/CA9G4N15JR8LDfJlc6LhRHnb/4C69ljOtHe8rUEAZ6MQmeShpf+RjrXSfDwIUiEIkaWyED8HJXKbsCkKlklfY+eV1g02lTZaDbS5EXpbAU2Thg71yXZDQRFrNaE7zFTxQuNQKtFeDVsn/8FsFWmI2XLjc0cvz2GHcoVCWLFRv3bjks+f0JFqcA9G2A1vrh0Z3i32DWtoTqAK6Y00Ry58L/Q/gvUSqwZbTAREWq1tyFS2yZuGoiLFodRzadVNvzYF/MK4ReNTPTlKgwzGnoaIUjgiH8FylKg4chWU9LNm7fr7Ju+e47+ZEw0FlYH1cd6F8ApERlq7Z5nphh8Zo0bkMMoVuJOwAUdOmUCOZiOu5IWzLX2/e/oYWlQCZNeHjKWAJk=
