apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: istio
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/kubeflow-onprem/argoflow.git
    targetRevision: v0.2.0
    path: distribution/istio
    kustomize:
      version: v4.0.5
  destination:
    server: https://kubernetes.default.svc
    namespace: istio-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
