kind: SealedSecret
apiVersion: bitnami.com/v1alpha1
metadata:
  name: cloudflare-api-token-secret
  namespace: kube-system
  creationTimestamp: null
spec:
  template:
    metadata:
      name: cloudflare-api-token-secret
      namespace: kube-system
      creationTimestamp: null
    data: null
  encryptedData:
    cloudflare_api_token: AgBmKIFXsXEOiuK4mlYNb9Mpz9M8YSEd/QCGMuHcXK+G1KQhNoswlclQYeg6Sxkjap9xkgd5G0tmflsP0Rb2l8Du494+udkMh5QT7qU9o/o66sC/Co2chp3hsLmSWsj0zgWGuvJMJPX83YRdceyRJVUjy3onVKGweKJW17MrYQQ+uDwsfrvgQYmDt3r7ovfu2dkqT5k8O/Ec2b4j49nNQzmJtTXE64ruptb6KI0wvAs2jgUu1HhvVkH0Kv0HfBIonO4kcLTDAkeI3T71k4QIAP+tw4jPvfHhd35m8YYIU1ApsPoKJ9YAq5JA8hTjiH4O1hrv+RTcAxhH1iGzHF3ieUrhWtY+u4id4kY4xRwXtF9EGK6V/sezkm37bp+sCNeCJLAPYTu+/kepPC+44daSccR3o+Dn9iA4O5q8Wme+AD/QDQ6vblgwoXnyDMLKUzF5H5yxjTPxwF/NJc6tE4GyFot3RnRRO7K8qq8Dg2pqGISQt9wxoOFciNlgw4AFtGgz/yU3ymcYTzCjH2VeJwZ6FuJdeQR72YcpPz84TjRXrzCnkwlfxNoMUinp8l9gthKKeG8M0+yJVLhOWp5U1w+AmGYgdpRx44GzTly7Nyo8RdSUHt5rbd9yB8KrkWmHJsAQgfty2l+wu2mPV44gto0gv7A6bOn/pX1jswbVj5MbU8fVX7GdyrJH2JAckyksOTYEFkXnsu9Un17Rf07D5RLgWJNENTVYxOdJZChJZ9xpPuwKZQOOZFwEa03h
