kind: SealedSecret
apiVersion: bitnami.com/v1alpha1
metadata:
  name: cloudflare-api-token-secret
  namespace: cert-manager
  creationTimestamp: null
spec:
  template:
    metadata:
      name: cloudflare-api-token-secret
      namespace: cert-manager
      creationTimestamp: null
    data: null
  encryptedData:
    api-token: AgBqXMgg5vmADz2HHJeObDjflQMLXB8OAz63ZnAiM57WKQHqGOrG+854eCjEdMKjQDhGj5PAfGaFCaJ++ETS3w6ZwQfS+ST6U2xU5hWm8t7E2XBCpw0iTRn7BWDeobUV5pueTHvGdicvKhiT8YjS6vxjDVLKQIu3LrNtlGP+BINqndGIw6erQMLEfogC7MvZkfIGpWf04LbyG8y5QWlXhecoaZsHpRp6limZAO/yw7czUelAiQndrykItCtG1H7pGqbjezpycMO38bRWkXpceH3zST7dz5JTzJ+1FViBhLdFkT4arKEuZu/tV2oCg87irHXNRO0M3iWSag9ulgNgw8sweDi40d39cHms6LSVIOb8jzGuZJu6kSW2PiuSb+ICS76uagWWdszsBqqRU5XIuVHoqwQjfvtt4MLymr+wh+Gt5nT55u+PB9byWSuAltAU9F6ln1cYVrSqWOGk47YpCN61aRcKFXC50V5gzERQHgwLX36RDdj7GwU0ZaV2QGis2A7mOBwnyPJJQizANmdShztCXvRDOSpTFjLtX++B6g5A4I6X8T7cRgISgzZHM4SqS4ZvRG3LS+0b93Ks8iXUlJ5TdzFJAyssxGPRMqQwjnJib5YxCwEgAjAkdRdjDi999o2vg7iw7UBAOLL3FURnWkFjHlFzSdby2RHs0RWRel7TREyTFA66UFXAYpc6ghQoF1ER+A9TyT9yMVZUqsJmULqOruYDPJyLRajpvFsRguBuuf1NpZLZL8aq
