kind: SealedSecret
apiVersion: bitnami.com/v1alpha1
metadata:
  name: grafana-admin-secret
  namespace: monitoring
  creationTimestamp: null
spec:
  template:
    metadata:
      name: grafana-admin-secret
      namespace: monitoring
      creationTimestamp: null
    data: null
  encryptedData:
    admin-password: AgCk31Uxume+DI2cTyEGVT8BGtHttDlY9+IUpM/OswFBco+upmd+v/PTbn/SzOjoiA0kuL850+BKyEa2IX/gh/nweoO6gPibcfbH3tv8HNq/b5aCeOlq0L3NxtP7azTLOTzvuDD1uwcd/dlQSFgPxY9H/TVWKge/UCQUsP17LrOt6A6ceBZDILq3XfJmmi1h+0qC5S+5Blt2/9OwI+fiA/dgkaXCSi0AUS444pg3dH+f9C2UM/t/ZftATubxiVPWWP62v/olHR1ykORAcx2yNqAEFSWTV04icXio5DBcrh0xQ/lLEYOdJ0wuvV3TL1xA2/Whiw7sGZKwT9Wdm4fLs4L/EmEfWAR4vR2tiCMbaD+F2Z/GV+RHYuXNjNkjI1ATHd7CEAwcGCYShkHL4JjcJJiJXcpxUkIiBvKpC34piLxet58i0/G/nh/5bY0qaDrxrFd+FMByVVtQLbBvyg7vgttI3gOB0RsNhcogEdsybMZoX8R4B9OGsJNpRiEGeXKMJscLxR9GXGJS915x5nJJ5Mxw56oVMbuGipF85m0yVllta/m5/ic+LA07hqu2++0KQ7qTdHOCZCEedG1my9gToncL4RAho1ZF1ozLm62fu7kgDUz2YW/2LsiiU/12E7o/7JdO1TBZ0yS7U326X8HuRr0HrbqV/kTeMl9dspl/s3EiufNgo9nLHXPcf/5EoRPhUCA2x3O+kS0=
    admin-user: AgA44c98g4MoSnvMV5ZszkoypShNdD5v3muFXZwC8ZfWH/csDdqdWSlVVUc817PbxyTMZ7TD5kkg0fQFCwnDW2U1BJBeWnoDzkDHcEqKB7+MPhq8ca5/tiqht+dWFkFFzhR/0BcuZFyu+n1hdjYXNutVvv87RQyytPCqDQcyk+CVQSaFIm/EAKAa1nnile+X57yr1bxLjr5zv65mnbBYmMQwZo+RERKT3hE5toEY4EJFrtv3SPhF9i9H+nnsfIlYLAn38G6kKffMnt1FKeFuirIL69ochm6Daw8OfETHUCClPoeALCYTlYxgbi9SPDJFkgVN+Wtq83Cj81/DwSCFic2/NU4AZTZXi+hLJcDxjwMtjAfA/DSQZ9Vy8fq/cOx1n8F1kzj1C54jWe/ig9uNaMwqEiFkEoAjzwPJrLf5vIuSeWN7npAwRNQvQgRxNZ92tjePijbL8ulrOrTztVd2M1hFbXY/Lf9JeZoSh6oBvX4E9iM+FH7Or4CoWBsVwJQdBD7IMHnLFE5Vd5m47BWqIWA2qnsJPkJx7HCXV5KmGrr5wMUzBdZIRR9FQVfXcnmtU84agI2caueqMacoKCkjkdjnTE66pj0cqQyZOSIkPDdfmjRX3ZCzL/rSYvtPjWxpg4J/oyyNqpNLMm2c7hM7ZGR6vXvRMunB3Hmp8pwKskcjkrxCT3Ecbn/JXVn/uxjCHjzO52+rbw==
